import { Service } from './types';

export const SERVICES: Service[] = [
  // TikTok Services
  {
    id: 'tiktok-views',
    name: 'TikTok Views',
    icon: 'Eye',
    platform: 'TikTok',
    description: 'Get more views on your TikTok videos instantly.',
    pricePer1000: 1,
    color: 'from-pink-500 to-rose-500',
  },
  {
    id: 'tiktok-likes',
    name: 'TikTok Likes',
    icon: 'Heart',
    platform: 'TikTok',
    description: 'Boost your TikTok posts with high-quality likes.',
    pricePer1000: 2,
    color: 'from-pink-600 to-rose-600',
  },
  {
    id: 'tiktok-followers',
    name: 'TikTok Followers',
    icon: 'Users',
    platform: 'TikTok',
    description: 'Grow your TikTok profile with real followers.',
    pricePer1000: 5,
    color: 'from-pink-700 to-rose-700',
  },
  {
    id: 'tiktok-pakistani-followers',
    name: 'TikTok Pakistani Followers',
    icon: 'UserPlus',
    platform: 'TikTok',
    description: 'Targeted Pakistani followers for your TikTok profile.',
    pricePer1000: 8,
    color: 'from-emerald-500 to-green-500',
  },

  // Instagram Services
  {
    id: 'instagram-views',
    name: 'Instagram Views',
    icon: 'Eye',
    platform: 'Instagram',
    description: 'Increase views on your Instagram reels and videos.',
    pricePer1000: 1,
    color: 'from-purple-500 to-indigo-500',
  },
  {
    id: 'instagram-likes',
    name: 'Instagram Likes',
    icon: 'Heart',
    platform: 'Instagram',
    description: 'Get more likes on your Instagram posts.',
    pricePer1000: 2,
    color: 'from-purple-600 to-indigo-600',
  },
  {
    id: 'instagram-followers',
    name: 'Instagram Followers',
    icon: 'Users',
    platform: 'Instagram',
    description: 'Grow your Instagram account with new followers.',
    pricePer1000: 5,
    color: 'from-purple-700 to-indigo-700',
  },
  {
    id: 'instagram-pakistani-followers',
    name: 'Instagram Pakistani Followers',
    icon: 'UserPlus',
    platform: 'Instagram',
    description: 'Real Pakistani followers for your Instagram profile.',
    pricePer1000: 8,
    color: 'from-emerald-600 to-green-600',
  },

  // Facebook Services
  {
    id: 'facebook-views',
    name: 'Facebook Views',
    icon: 'Eye',
    platform: 'Facebook',
    description: 'Boost views on your Facebook videos and reels.',
    pricePer1000: 1,
    color: 'from-blue-500 to-cyan-500',
  },
  {
    id: 'facebook-likes',
    name: 'Facebook Likes',
    icon: 'Heart',
    platform: 'Facebook',
    description: 'Get more likes on your Facebook posts and pages.',
    pricePer1000: 2,
    color: 'from-blue-600 to-cyan-600',
  },
  {
    id: 'facebook-followers',
    name: 'Facebook Followers',
    icon: 'Users',
    platform: 'Facebook',
    description: 'Increase your Facebook profile or page followers.',
    pricePer1000: 5,
    color: 'from-blue-700 to-cyan-700',
  },
  {
    id: 'facebook-pakistani-followers',
    name: 'Facebook Pakistani Followers',
    icon: 'UserPlus',
    platform: 'Facebook',
    description: 'Targeted Pakistani followers for your Facebook profile.',
    pricePer1000: 8,
    color: 'from-emerald-700 to-green-700',
  },
];
